### ISSUE TITLE
shader消えない問題

### ISSUE THREAD

**Issue by sakeida** [sakeida/noise#1]
ENDflagとGlitchFXというスクリプトで問題が起きています。

それぞれのスクリプトについて
GlitchFX：ノイズをカメラに出力
ENDflag：エンディングの分岐に関係するアイテムに適応。プレイヤーが取得時にプレイヤーのFLAG変数をインクリメント、オブジェクトの削除、came(プレイヤーのカメラ）のコンポーネントであるGlitchFXのなかのintensity（ノイズの強度）を0.5に変更コルーチンの開始

やりたいことノイズ発生　＝＞　数秒後にノイズを停止

・試したことenabled()によるコンポーネントの停止
・intensity=0;

どちらも上手くいかず困っています。お助けください。

**Comment by Ayarin226** [comment]
どううまくいかないのだろうか？
現状はどうなっているの？

**Comment by sakeida** [comment]
今はノイズ発生後消えない状態です

**Comment by Ayarin226** [comment]
どのシーンで確認できますかー？

**Comment by sakeida** [comment]
シーン1を進んだ先にあるlootbox(名前、不確か)の中のmodelに適応しています

**Comment by Ayarin226** [comment]
`intensity=0;` でも `enabled()` でもノイズは消えます。
`ENDflag` がついている 2Gears_low が非アクティブだけどそれは関係ないのかな？
分岐に関係するアイテムをどうやって取得するのかが分からないのでなんとも言えないけれど……

**Comment by Ayarin226** [comment]
やっと言っている意味が分かった
```
 if (col.gameObject.tag == "player")
        {

            Destroy(this.gameObject);
            PlayerController.FLAG++;
            player = came.GetComponent<GlitchFx>();
            player.intensity = 0.5f;
            StartCoroutine("NOISE");
        }
```
ここだね。
一番最初に `Destroy(this.gameObject);` をしてしまっているから、そのあとの処理が全て呼ばれていないね。 `Destroy(this.gameObject);` を一番最後に回してあげれば出来るかと。
このまま一番最後に回しても、コルーチンで1秒待っている間に `Destroy()` されてしまうのは注意！

**Comment by sakeida** [comment]
なるほど理解できました。
深夜遅くにありがとうございます

**Comment by sakeida** [comment]
手元のパソコンの電源が切れる＆外出中ゆえ不確かな情報で混乱させてしまいすみませんでした。
重ねてありがとうございました
